name: "Scheduled jobs"
on:
  schedule:
    - cron: "0 */2 * * *"
jobs:
  post-art:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        with:
          working-directory: "./"
          stack-yaml: "stack.yaml"
          test: false
      - name: "Creating .env"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: "Build and run"
        run: stack build && stack exec botinari-exe
